#BNF+IAT 1.0 UTF-8;
!grammar call;
!slot <role>;
!slot <action>;
!slot <injectionAct>;
!slot <enquire>;
!slot <term>;
!slot <drugs>;
!slot <value>;
!slot <unit>;
!start <commands>;
<commands>:<currency>|<injection>|<enquire>|<prepare>;
<role>:李医生|张医生|杨护士|王护士|病人|患者|医生|家属|管理员|技师|李四;
<action>:上|下|下达|建立|安装|启动|开放|进行|行|测|监测|查|查看|评估|采集|准备|停止|向家属|是|出现|误吸致|执行|记录|开始|结束|提供|调整;
<injectionAct>:推注|注射|静脉滴注|静脉推注|肌肉注射|皮下注射|静脉注射|输入|给予;
<enquire>:你怎么了|哪里不舒服|哪里痛|我给你检查;
<term>:病历|心电监护|静脉通路|另一条静脉通路|骨内输液|中心静脉置管|静脉采血|心脏按压|按压|停止按压|暂停按压|交换角色继续按压|继续按压|应急系统|除颤|分析心率|吸氧|面罩吸氧|面罩给氧|心肺复苏|心脏室颤|动脉穿刺|动脉采血|血气分析|床旁心电图|床旁超声|简易呼吸器通路|气管插管|负压吸痰|喉罩|气管切开术|导尿术|导尿|胃管置入|三腔两囊管|抬高下肢|摇床|偏头|输血|吸痰|开放气道|血常规|凝血功能|血糖|肝肾功能|电解质|血型|合血|补液|血压|双上肢血压|低温|查体|心脏查体|胸部查体|全身查体|呼吸|脉搏|瞳孔|嘴唇|呼吸脉搏恢复|除颤|护脑|促醒|生命征|神志瞳孔|尿量|B超|胸片|胃镜|头颅CT|采集病史|病危|知情同意书|上消化道大出血|轻度休克|呼吸道梗阻|生命体征|复查气血|转ICU|内环境平衡|诊疗计划|禁食|家属沟通|浅昏迷;
<drugs>:吡罗昔康|阿糖腺苷|加巴喷丁|硝苯地平|普罗帕酮|多西他赛|奥沙利铂|氟尿嘧啶|亚胺培南西司他丁钠|头孢哌酮舒巴坦钠|克林霉素磷酸酯|羧甲司坦|腺苷|胺碘酮|阿托品|多巴胺|肾上腺素|盐酸异丙肾上腺素|利多卡因|异博定|盐酸维拉帕米|洛贝林|盐酸山梗菜碱|氨茶碱|尼可刹米|可拉明|阿拉明|重酒石酸间羟胺|西地兰|速尿|呋塞米|安定|地西泮|地塞米松|6542|山莨菪碱|复发氯化钠|奥美拉唑|生长抑素|奥曲肽|胰岛素;
<value>:零点一|零点二|零点三|零点五|一点五|二点五|零点七|三点五|四点五|五点五|六点五|七点五|八点五|九点五|十|十五|十八|二十|三十|四十|五十|五十五|五百五十五|六十|七十|八十|九十|一百|一百一十|一百二十|一百三十|一百四十|一百五十|一百六十|一百七十|一百八十|一百九十|两百|二百|两百一十|二百一十|二百二十|两百二十|二百三十|两百三十|二百四十|两百四十|二百五十|两百五十|二百六十|两百六十|二百七十|两百七十|二百八十|两百八十|二百九十|两百九十|三百|三百一十|三百二十|三百三十|三百四十|三百五十|三百六十|三百七十|四百五十|六百|七百五十|九百|一千零五十|一千两百|一千两百|一千三百五十|一千五百|一千六百五十|一千八百|一千九百五十|两千一百|两千两百五十|两千二百五十|两千四百|两千五百五十|两千七百|两千八百五十|三千|一|两|二|三|四|五|六|七|八|九|一千|两千;
<unit>:微克|毫克|克|毫升|分|焦耳|度;
<crap>:请|可能|认为|让|为|请为|目前|立即;
<currency>:[<crap>][<role>][<action>]<term>|[<crap>][<action>]<term>[<role>]|[<crap>][<role>][<action>]<term>[<value>][<unit>]|[<role>][<crap>][<action>]<term>|[<role>][<injectionAct>][<term>];
<injection>:[<crap>][<role>]<injectionAct><drugs><value>[<unit>]|[<crap>][<role>]<drugs><value>[<unit>]<injectionAct>|[<crap>][<role>]<value>[<unit>]<drugs><injectionAct>;
<prepare>:[<crap>][<role>]<action><drugs>[<value>][<unit>]|[<crap>]<action><drugs>[<value>][<unit>][<role>]|[<crap>][<role>]<action>[<value>][<unit>]<drugs>;